<?php

use yii\db\Migration;

class m160729_203255_add_to_album_table_1950s extends Migration
{
    /*public function up()
    {

    }

    public function down()
    {
        echo "m160729_203255_add_to_album_table_1950s cannot be reverted.\n";

        return false;
    }*/

    public function safeUp()
    {
        $data = [
            [
                1,
                1,
                'In The Wee Small Hour',
                1955,
                'Capitol',
                'Voyle Gilmore',
                'Tommy Steele',
                'USA',
                '00:50:25',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                2,
                2,
                'Elvis Presley',
                1956,
                'RCA',
                'Uncredited',
                'William V. Robertson',
                'USA',
                '00:28:42',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                3,
                3,
                'Tragic Songs Of Life',
                1956,
                'Capitol',
                'Ken Nelson',
                'Uncredited',
                'USA',
                '00:35:58',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                4,
                4,
                'The Wildest!',
                1956,
                'Capitol',
                'Voyle Gilmore',
                'Uncredited',
                'USA',
                '00:32:00',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                5,
                5,
                'This Is Fats',
                1956,
                'Imperial',
                'Dave Bartholomew',
                'Uncredited',
                'USA',
                '00:27:11',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                6,
                6,
                'Ellington At Newport',
                1956,
                'Columbia',
                'George Avakian',
                'Uncredited',
                'USA',
                '00:44:00',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                7,
                1,
                'Songs For Swingin\' Lovers!',
                1956,
                'Capitol',
                'Voyle Gilmore',
                'Uncredited',
                'USA',
                '00:45:00',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                8,
                7,
                'The "Chirping" Crickets',
                1957,
                'Brunswick',
                'Norman Petty',
                'Uncredited',
                'USA',
                '00:25:59',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                9,
                8,
                'The Atomic Mr.Basie',
                1957,
                'Roulette',
                'Teddy Reig',
                'Uncredited',
                'USA',
                '00:39:30',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                10,
                9,
                'Brilliant Corners',
                1957,
                'Riverside',
                'Orrin Keepnews',
                'Paul Bacon',
                'USA',
                '00:43:08',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                11,
                10,
                'Palo Congo',
                1957,
                'Blue Note',
                'Alfred Lion',
                'Reid Miles',
                'USA',
                '00:40:52',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                12,
                11,
                'Birth Of The Cool',
                1957,
                'Capitol',
                'Pete Rugolo',
                'Uncredited',
                'USA',
                '00:37:59',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                13,
                12,
                'Kenya',
                1957,
                'Roulette Jazz',
                'Ralph Seijo',
                'Uncredited',
                'USA',
                '00:35:46',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                14,
                13,
                'Here\'s Little Richard',
                1957,
                'Specialty',
                'Bumps Blackwell',
                'Thadd Roark',
                'USA',
                '00:27:31',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                15,
                14,
                'Dance Mania, Vol. 1',
                1958,
                'BMG',
                'Uncredited',
                'Uncredited',
                'USA',
                '00:38:41',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                16,
                15,
                'Lady In Satin',
                1958,
                'Columbia',
                'Irving Townsend',
                'Uncredited',
                'USA',
                '00:39:10',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                17,
                16,
                'Jack Takes The Floor',
                1958,
                'Topic',
                'Bill Leader, Dick Swettenham',
                'Uncredited',
                'USA',
                '00:31:45',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                18,
                17,
                'Sarah Vaughan At Mister Kelly\'s',
                1958,
                'EmArcy',
                'Bob Shad',
                'Uncredited',
                'USA',
                '00:37:00',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                19,
                18,
                'Sings The Gershwin Song Book',
                1959,
                'Verve',
                'Norman Granz',
                'Bernard Buffet',
                'USA',
                '03:14:10',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                20,
                19,
                'The Genius Of Ray Charles',
                1959,
                'Atlantic',
                'Nesuhi Ertegun',
                'Marvin Israel',
                'USA',
                '00:37:58',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                21,
                11,
                'King Of Blue',
                1959,
                'Columbia',
                'Irving Townsend',
                'Jay Maisel',
                'USA',
                '00:45:52',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                22,
                20,
                'Gunfighter Ballads And Trail Songs',
                1959,
                'CBS',
                'Don Law',
                'Howard Fritzson',
                'USA',
                '00:35:53',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
            [
                23,
                21,
                'Time Out',
                1959,
                'Columbia',
                'Teo Macero',
                'Uncredited',
                'USA',
                '00:38:21',
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac ullamcorper orci. Fusce ac lacus.',
                '',
            ],
        ];
        $this->batchInsert('album',
            [
            'id',
            'author_id',
            'name',
            'year',
            'label',
            'producer',
            'art_direction',
            'nationality',
            'running_time',
            'description',
            'image'
            ],
            $data);
    }

    public function safeDown()
    {
        $this->delete('album',['between', 'id', 1, 23]);
    }

}
